### ISSUE TITLE
[Q] why using dailab/libsml?

### ISSUE THREAD

**Issue by curlyel** [oetken/smartmetertomqtt#1]
... instead of https://github.com/volkszaehler/libsml ?

Is there some drawback with the newer/actively maintained libsml?

**Comment by oetken** [comment]
No there is no drawback. Tested and works fine. Thanks.

**Comment by oetken** [comment]
@curlyel If you have any further issues feel free to ask.

**Comment by curlyel** [comment]
Hi Andreas,
thanks for clarifying/merging the "maintained" lib ;-)

> further issues feel free to ask

Well, one thing though ;-)
Not related to the lib...

Have you considered creating a **_third_ filter for _debouncing_ readings** beside _mean_ and _skip_?
I've checked your code and if I unterstand correctly,

**_mean_** - calculates a sliding average over _windowSize_ number of readings before publishing
**_skip_** - simply skips skipCount readings before publishing the next value

Quite useful from my point of view would be:
**_debounce_** - basically quite similar to _mean_, BUT publishes _immediately_ if the reading of a datapoint has changed remarkably (higher than a configured change threshold).

_Example:_
When someone is after current power readings he/she likely don't want to publish every tiny change of e.g. 5 Watts to the mqtt broker which triggers subsequent processing. I guess this was the initial intention for your _mean_ and _skip_ filters. So in general, a reading update every minute might be sufficient usually. BUT if some device get switched on drawing a hight amount of power, you like to react immediately and not wait for the next minute's mqtt publish of the _mean_ value.

So if the current power readings changes by more than the configured amount (e.g. 1000Watt), the power reading should be published immediately, probably by sending the _mean_ (which has been calculated til the big change so far) first followed immediately by the _current_ reading.

This could bring a good balance between fewer messages but still the possibility to quick response to big changes in curren power.

**Comment by oetken** [comment]
Very nice idea. If I find some spare time I will take care of it. You might open a new issue if you like otherwise I willopen one and quote you.

**Comment by curlyel** [comment]
done:  https://github.com/oetken/smartmetertomqtt/issues/3
